# AutoText
# Preenchedor de textos prontos
# Autor: Tom-Dev-Full
# 2023

# 1. SELECIONAR E COLAR TEXTO

  # 1.1 ABRIR ARQUIVO COM O TEXTO

  # 1.2 SELECIONAR O TEXTO

  # 1.3 COLAR TEXTO

# 2. GERENCIAR TEXTOS

  # 2.1 CRIAR TEXTO
    # 2.1.1 CRIAR ARQUIVO EM MODO DE ESCRITA E ACRESCENTAR TEXTO
    # 2.1.2 VERIFICAR SE JÁ EXISTE
    # 2.1.3 SELECIONAR TIPO *
    # 2.1.4 ORGANIZAR TEXTOS POR TIPOS (E-MAIL, SAJ, WORD, ETC.) *

  # 2.2 EDITAR TEXTO
    # 2.2.1 COLAR TEXTO EM UMA VARIÁVEL, EDITÁ-LO, ABRIR O RESPECTIVO ARQUIVO E SUBSTITUIR O TEXTO

  # 2.3 EXCLUIR TEXTO
    # 2.3.1 APAGAR ARQUIVO

# 3. MOSTRAR RECENTES

  # 3.1 SALVAR O ID DOS ÚLTMIMOS TEXTOS EM UMA LISTA OU ARQUIVO
    # 3.1.1 SUBSTITUIR O PRIMEIRO PELO ANTECESSOR

  # 3.2 SELECIONAR O TEXTO DE ACORDO COM O ID

# 4. APRESENTAR AS OPÇÕES DE TEXTOS

